### ISSUE TITLE
It does not work.

### ISSUE THREAD

**Issue by luisalrp** [hummingbot/streamlit-apps#6]
It does not work. Not sure how to help :/

<img width="582" alt="image" src="https://user-images.githubusercontent.com/31384138/223445095-601e4fc7-783b-4731-828b-3b27123c01b0.png">

**Comment by klpanagi** [comment]
This issue is related to bugs reported in the building process.
I have created a PR that addresses this issue https://github.com/hummingbot/streamlit-apps/pull/7 .
